---
- name: Set docker-ce package state to latest
  set_fact:
    docker_pkg_state: 'latest'

- name: Ensure docker-ce is installed
  package:
    name: docker-ce
    state: present
  become: true

- name: start docker
  service:
    name: docker
    state: started
  become: yes
